package com.smg.art.db.database;

import com.smg.art.db.entity.RongUserInfoEntity;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig rongUserInfoEntityDaoConfig;

    private final RongUserInfoEntityDao rongUserInfoEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        rongUserInfoEntityDaoConfig = daoConfigMap.get(RongUserInfoEntityDao.class).clone();
        rongUserInfoEntityDaoConfig.initIdentityScope(type);

        rongUserInfoEntityDao = new RongUserInfoEntityDao(rongUserInfoEntityDaoConfig, this);

        registerDao(RongUserInfoEntity.class, rongUserInfoEntityDao);
    }
    
    public void clear() {
        rongUserInfoEntityDaoConfig.clearIdentityScope();
    }

    public RongUserInfoEntityDao getRongUserInfoEntityDao() {
        return rongUserInfoEntityDao;
    }

}
